name: CI

on: [push, pull_request]

jobs:
  fast-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint with Ruff
        uses: astral-sh/ruff-action@v1
        with:
          args: check .

      - name: Check formatting with Ruff
        uses: astral-sh/ruff-action@v1
        with:
          args: format --check

      - name: Run tests using system Python
        run: python3 -m unittest discover -p '*test.py'
