name: CI

on: [push, pull_request]

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint with Ruff
        uses: astral-sh/ruff-action@v1
        with:
          args: check .

      - name: Check formatting with Ruff
        uses: astral-sh/ruff-action@v1
        with:
          args: format --check

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build zstd_stream
        run: cd presume && go mod init zstd_stream && go mod tidy && go build

      - name: Run go tests
        run: cd presume && go test

      - name: Run tests using system Python
        env:
          RCARCH_ZSTD_STREAM: "${{ github.workspace }}/presume/zstd_stream"
        run: python3 -m unittest discover -p '*test.py'
